### ISSUE TITLE
[BUG] I'm trying to replicatee something closer to the PROPERTY macro in Qt

### ISSUE THREAD

**Issue by patrickelectric** [GoogleFeud/ts-macros#12]
**Describe the bug**
Does not work inside classes

**Code to reproduce**
```
function $property() {
    property = 0
}

$property!()

export class ArduPilotSub extends Vehicle.Abstract {
    $property!()

    constructor() {
        super(Vehicle.Firmware.ArduPilot, Vehicle.Type.Sub)
    }
}
```

[link](https://googlefeud.github.io/ts-macros/playground/?code=GYVwdgxgLglg9mABAEgA4Cc6oKbqgTwAoBKRAbwChFrEMtcDEBeRABgoF8KK1Mc98AQhLdsAD1Rw8iCABsAhgGdFiAILoAJiAAKMWXCgBlEACNE4qNjAaVANWwALGHOwA6VScVR086OSo0vPQCwsTcNDIIXugg0FIk-hERiiD8hPZOLq4AYjDoALYA7vLobupauvpQADSIGc6ybgAq+DiuxiZhEVwcQA)

**Expected behavior**
The output would be something like:
```
export class ArduPilotSub extends Vehicle.Abstract {
    property = 0;
    constructor() {
        super(Vehicle.Firmware.ArduPilot, Vehicle.Type.Sub);
    }
}
```
Ref: https://doc.qt.io/qt-5/properties.html

**Additional context**
It would be nice to have more examples, like:
How do I use a type as a parameter.
`$macro!(number, test, 0)`
Generating something like:
`const test: number = 0`

**Comment by GoogleFeud** [comment]
Yeah, this is not possible currently because macro calls are just regular function calls, you can only use them where you can call functions :(
