### ISSUE TITLE
[BUG] Does not actually process macros

### ISSUE THREAD

**Issue by pnijo** [GoogleFeud/ts-macros#14]
**Describe the bug**
When I build the project macros are not processed. There is no form of troubleshooting available and cannot locate any resources on how to fix this.

The instructions provided have not worked for me

**Code to reproduce**
Code I have works on the playground and not in my project. Code provided in the documentation does not work for me.

**Expected behavior**
That the macros would actually be processed

**Additional context**
I have `ttypescript` added as a dev dependency along with `ts-macros`
I have added the plugin to `tsconfig.json` although it says `ts-docs` and then writes `ts-macros` but neither work (also the intentation is weird with `plugins` on the same level as `compilerOptions` and yet `plugins` is a child)
I tried out my code in the playground beforehand and even copied over some of the examples and they don't work either.

**Comment by GoogleFeud** [comment]
Hey! What command do you use to transpile your code? You must use `ttsc`, which uses `ttypescript` instead of `typescript`.

I should add that to the documentation, and also fix the issues you mentioned in the issue. Thanks!

**Comment by pnijo** [comment]
Ah I see, was not aware I needed to use `ttsc`, thank you.
