### ISSUE TITLE
[BUG] macro not work properly after 1.3.4

### ISSUE THREAD

**Issue by noname0310** [GoogleFeud/ts-macros#17]
**Describe the bug**

When you split a file, the macro behaves strangely

**Code to reproduce**
Paste the relevant code which reproduces the error, or give detailed instructions on how to reproduce it.

input: 
```typescript
// test.ts
export function $m1() {
    return 1;
}
```
```typescript
// index.ts
import { $m1 } from "./test";

const m1 = $m1!();
m1;
```
output:
```typescript
// index.js
import { $m1 } from "../test";
const m1 = null;
m1;
```

**Expected behavior**

```typescript
// index.js
import { $m1 } from "../test";
const m1 = 1;
m1;
```

**Additional context**

It should also be possible to duplicate the names of macros on a file-by-file basis

For example, if `file1.ts` has a macro named `m1` and `file2.ts` has a macro named `m1`, you should be able to use the macro you want, depending on which one you import.

```typescript
// file1.ts
export function $m1() {
    return 1;
}
```
```typescript
// file2.ts
export function $m1() {
    return 2;
}
```

```typescript
// index.ts
import { $m1 } from './file1';
import { $m1 as $m2 } from './file2';

const test = $m1!(); // it should be 1
const test = $m2!(); // it should be 2
```

**Comment by GoogleFeud** [comment]
Fixed!

**Comment by noname0310** [comment]
> Fixed!

Thank you very much. This transformer is now used for `js-sdsl`. I hope there's no fatal bug...

**Comment by GoogleFeud** [comment]
I'm confident everything's working, but if you encounter something I'll get it fixed asap :)!
