### ISSUE TITLE
[BUG]macros chaining problem

### ISSUE THREAD

**Issue by noname0310** [GoogleFeud/ts-macros#18]
**Describe the bug**

macros chaning not works properly

**Code to reproduce**
Paste the relevant code which reproduces the error, or give detailed instructions on how to reproduce it.

input:
```typescript
// Vector2.ts
export namespace Vector2 {
    export function $new(): Vector2 {
        return [0, 0] as unknown as Vector2;
    }
}

export interface Vector2 {
    $x(): number;
    $y(): number;
}

function $asData(v: Vector2): [number, number] {
    return v as unknown as [number, number];
}

export function $x(v: Vector2): number {
    return $asData!(v)[0];
}

export function $y(v: Vector2): number {
    return $asData!(v)[1];
}
```

```typescript
//index.ts
import { Vector2 } from "./Vector2";

const vec1 = Vector2.$new!();
console.log(vec1.$x!());
console.log(vec1.$y!());
```

output:
```javascript
import { Vector2 } from "./Vector2";
const vec1 = [0, 0];
console.log(null);
console.log(null);
```

**Expected behavior**

output should be:
```javascript
import { Vector2 } from "./Vector2";
const vec1 = [0, 0];
console.log(vec1[0]);
console.log(vec1[1]);
```

**Additional context**

In version 1.3.3, you saved the name, not the symbol of the macro,
so it would have been possible to decide which macro to map to when chaining.

However, by storing symbols, it became impossible to know which macro to map to when chaining.
So to solve this problem, I think we need a syntax that determines which macro to actually map to when declaring a macro member on an interface.

for example:
```typescript
//new builtin function
type Keys<T> = {
    [K in keyof T]: T[K] extends Function ? K : never;
}[keyof T];

type ReturnType<T> = T extends (...args: any[]) => infer R ? R : any;

type MacroMap<T> = {
    [K in Keys<T>]: (v: T) => ReturnType<T[K]>;
};

export function $$macroMapper<T, M extends MacroMap<T> = MacroMap<T>>(map: M): void {
    map;
}
```
```typescript
export namespace Vector2 {
    export function $new(): Vector2 {
        return [0, 0] as unknown as Vector2;
    }
}

export interface Vector2 {
    $x(): number;
    $y(): number;
}

function $asData(v: Vector2): [number, number] {
    return v as unknown as [number, number];
}

export function $x(v: Vector2): number {
    return $asData!(v)[0];
}

export function $y(v: Vector2): number {
    return $asData!(v)[1];
}

$$macroMapper<Vector2>({
    $x: $x,
    $y: $y
}); // now we know what macro to map.
```

**Comment by GoogleFeud** [comment]
Thanks! This was completely overlooked, lol! I'm gonna think about this and update tomorrow, but the best solution I can think of without adding any new syntax is comparing the argument types provided to the macro, so, in your example, the transpiler would only throw an error if:

- There is another function with the name `$x`, which has `Vector2` as the first parameter
- That same function is used in chaining, if it's not used in chaining at all it won't error

I'll see what I can do :)!

**Comment by GoogleFeud** [comment]
Fixed! You can read up on how chaining works [here](https://googlefeud.github.io/ts-macros/pages/In-Depth/Chaining%20Macros.html)
