### ISSUE TITLE
[BUG] extending interfaces with macros doesn't work with Angular

### ISSUE THREAD

**Issue by AlariOis** [GoogleFeud/ts-macros#22]
I was able to integrate ts-macros to Angular14 application using ngx-build-plus library.

**Describe the bug**
My $contains macro works when calling it like
```
const needle = 'three';
const haystack = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'];

this.needle_found = $contains!(this.needle, ...this.haystack );
```

the macro itself
```
export function $contains<T>(value: T, ...possible: Array<T>): boolean {
  return possible.includes(value);
}
```

But the project does not compile when trying to extend String interface with it.
The error message:
error TS8000: No possible candidates for "$contains" call

```
declare global {
  interface String {
    $contains<T>(...possible: Array<T>) : boolean;
  }
}

this.needle_found = this.needle.$contains!(...this.haystack);
```

**Code to reproduce**
Here is a quick bare bones project to reproduce the error
https://github.com/AlariOis/angular-ts-macros

I know that messing around with private Angular build system API is a good way to shoot yourself in the foot and there is a good chance the problem is not with ts-macros.
Just to clarify - both examples work fine on my node backend, it is the Angular project that has the issue.

**Comment by GoogleFeud** [comment]
Thanks for the issue! Currently, macros meant to be chained cannot accept type parameters as their first parameter. You can work around this by using `any` for the first parameter (which in this case sort of defeats the point of generics, but good to know regardless):
```ts
export function $contains<T>(value: any, ...possible: Array<T>): boolean {
  return possible.includes(value);
}
```
I think I'll fix this by treating generic types as `any` so errors like this one don't come up.

**Comment by AlariOis** [comment]
Thanks! That worked!

Now though when I use hot reload and change the file that has macros in it, I get the same 'no possible candidate error'.
I believe this bug was present in 1.3.3 for all macros.  Then the error was 'macro already defined' or something like that. Now it works perfectly for 'normal' macros but breaks for chained macros.

But I keep my macros in a separate file for reusability and I just have to recompile the project when changing macros.

So I am super happy with this workaround!

Maybe the readme example should also mention that, for chaining, the first parameter cannot be a generic?

**Comment by GoogleFeud** [comment]
> Now though when I use hot reload and change the file that has macros in it, I get the same 'no possible candidate error'.
I believe this bug was present in 1.3.3 for all macros. Then the error was 'macro already defined' or something like that. Now it works perfectly for 'normal' macros but breaks for chained macros.

Interesting! I'll try to replicate it.

> Maybe the readme example should also mention that, for chaining, the first parameter cannot be a generic.

I'll make it so generic traits are treated like `any` so this error never comes up!
