### ISSUE TITLE
[BUG] Unable to import macros from files

### ISSUE THREAD

**Issue by MrHands** [GoogleFeud/ts-macros#29]
I'm trying to create a logging macro for Typescript that I want to use across my project.

Using a macro inside the same file works:
```
// replication.ts

function $logInfo(domain: string | object, message: string) {
	console.log(`(${domain}) ${message}`);
}

class Replication {
	static toString() {
		return 'Replication';
	}

	static connect() {
		$logInfo!(this, 'connect');
	}
}

// index.bundle.js

class Replication {
    static toString() {
        return 'Replication';
    }
    static connect() {
        console.log(`(${this}) ${"connect"}`);
    }
}
```
I bundle my Typescript with Webpack using the `ts-loader`.

But if try to import my macro from another file, my macro is omitted entirely from the bundled output:
```
// logging.ts

function $logInfo(domain: string | object, message: string) {
	console.log(`(${domain}) ${message}`);
}

export {
	$logInfo,
};

// replication.ts

import {
	$logInfo 
} from './logging';

class Replication {
	static toString() {
		return 'Replication';
	}

	static connect() {
		$logInfo!(this, 'connect');
	}
}

// index.bundle.js

class Replication {
    static toString() {
        return 'Replication';
    }
    static connect() {
    }
}
```
I would like to know what the best practices are when it comes to sharing macros between files.

Here's the relevant portion of my Webpack configuration:
```
module: {
	rules: [
		// compile typescript

		{
			test: /\.ts$/,
			exclude: /node_modules/,
			use: [
				{
					loader: 'ts-loader',
					options: {
						configFile: 'tsconfig.json',
						compilerOptions: {
							soureMap: Boolean(devtool),
							outDir: path.resolve(targetPath, 'js')
						},
						getCustomTransformers: (program) => ({
							before: [TsMacros.default(program)]
						}),
					},
				},
			],
		},
	],
],
````

**Comment by joehinkle11** [comment]
I have the same problem. Haven't looked into it yet as everything is in one big file still

**Comment by GoogleFeud** [comment]
Interestingly, this isn't the first time a similar bug has been reported. In #23 the transformer works correctly between files when used with `@rollup/plugin-typescript`, but it doesn't work with `rollup-plugin-ts`. Your code works correctly when using `ttypescript`, but fails when using `ts-loader`. I don't have much time right now but I'll look into it later today!

(Unrelated issue but as I was testing this code I found another bug - template literals get messed up when used in macros which get used in other files, I'll post a fix on that asap as well as support for 4.9.4)

**Comment by joehinkle11** [comment]
Okay, it isn't critical for me at least. I just finished my big refactor and I ended up not needing to use the macros in multiple files.

**Comment by GoogleFeud** [comment]
I think it comes down to `ts-loader` and how it decides to go through each file. This is the order of the files `ttypescript` (and typescript) will give to the transformer:
```
logging.ts
replication.ts
```
and here's ts-loaders:
```
replication.ts
logging.ts
```
so the transformer first goes through `replication.ts`, and sees a used macro but cannot find any instances of it, so it just expands it to nothing.

I could try to fix it on the transformer's end, but I think it's an issue on ts-loader's end - it should have the same behaviour as typescript.

**Comment by MrHands** [comment]
Thank you for the quick responses!

I ultimately solved my problem by moving away from `ts-macros` in favor of [rolling my own transform function](https://cohost.org/mrhands/post/618370-i-fell-down-a-rabbit), which I think is a damn shame because your library provides a much smoother user experience.

I believe you when you say the issue is with `ts-loader` and not your code; it's a complicated web of dependencies to get this running in the first place!

**Comment by MrHands** [comment]
Thanks for the suggestions!

It's interesting to me that an if-else would have worked better for my macro. I assumed that because the return statement was showing up in the output, the macro would always duplicate the function body without any further processing. The reason I wrote it in this way was that I've set up my linter to warn me when an else-statement could have been an early-out instead. :D

I hope you can resolve this issue with the `ts-loader` project. I'm satisfied with my workaround for now, at least.

**Comment by GoogleFeud** [comment]
I decided to fix this issue in the transformer, so if any future package messes with the order of the files, it won't matter :). You should be able to use it now!
