### ISSUE TITLE
How to escape $$inlineFunc macro?

### ISSUE THREAD

**Issue by darky** [GoogleFeud/ts-macros#36]
Hello! 

I try to write something like this: 
https://googlefeud.github.io/ts-macros/playground/?code=FAehAIEkDsBcFMBOBDAxrAlgN3uADgDbICeA5ogPYCu0AJgISgQDqiGC4x1i4qFtuABZJcyOuADO8XLGHhYKaBLwYC8WuETwJVArAB0TcAEECBecTzbwYjQDMa6DBSXg7lALby5BDACMURGIbLRsCLWRaYIwPPApEBAZgYAdoJxdwABIPZDwAHgAVABpwACUAPgAKZEREAC5wAGVkHDzjWpJC8vKS1D8GyvZ4DwaCgEpwAF5ysomG9pRiPIrwAG9gcE2szO1UXPh6SsqJ6bWNrYu+JVhNa0nwAG0AXQBuc4vNu3jwSrUbjEmAAYXuAMOA8iFEPo1NBSLIQRgANSIibrD4fK4SG54KgSYQae6ZHYSPZWQ7HKYzIkYaC+aDwABijkOfRKNUQDwwTzGYze6IuWgk+hxeMqIvxvPeHwAvlLpZKBfBYFRENBthgBHBDgAiQXayWy4BHE4zNFbbK5Q4PACMJQATCUAMwlAAsJQArCUAGwlADsJQAHCUAJxPEqVaBUDwmta3ZWq8CRrwAKnAdpB8pBYHAHl0mHAdNwqVQwHlxzeQA

But emitted result not expected:

```ts
(() => {
    return arr_1[i_1] * 2;
})();
const pushed_1 = null;
```

Want to see something like this:

```ts
const pushed = arr_1[i_1] * 2;
const pushed_1 = pushed;
```

I know, that `$$inlineFunc` can be passed directly to variable:
https://googlefeud.github.io/ts-macros/playground/?code=FAehAIEkDsBcFMBOBDAxrAlgN3uADgDbICeA5ogPYCu0AJgISgQDqiGC4x1i4qFtuABZJcyOuADO8XLGHhYKaBLwYC8WuETwJVArAB0TcAEECBecTzbwYjQDMa6DBSXg7lALby5BDACMURGIbLRsCLWRaYIwPPApEBAZgYAdoJxdwABIPZDwAHgAVABpwACUAPgAKZEREAC5wAGVkHDzjWpJC8vKS1D8GyvZ4DwaCgEpwAF5ysomG9pRiPIrwAG9gcE2szO1UXPh6SsqJ6bWNrYu+JVhNa0nwAG0AXQBuc4vNu3jwSrUbjEmAAYXuAMOA8iFEPo1NBSLIQRgANSIibrD4fK4SG54KgSYQae6ZTIYaC+aDwABijkOfRKNUQDwwTzGb3RFy0En0OLxlW5+JZ7w+AF9BUKBez4LAqIhoNsMAI4IcAEQcpUCkXAI4nGZorbZXKHB4ARhKACYSgBmEoAFhKAFYSgA2EoAdhKAA4SgBOJ4lSrQKgebVrW5SmXgANeABU4FNILFILA4A8ukw4DJuFSqGAYuObyAA

But self-executing function has additional runtime cost and desire to avoid it totally:

```ts
const pushed_1 = (() => {
    return arr_1[i_1] * 2;
})();
res_1.push(pushed_1);
```

**Comment by GoogleFeud** [comment]
Hi, thanks for the issue! I think it'd be a good idea to remove `$$inlineFunc` in the next big update, and merge it into `$$escape`. The merge will happen in the next minor update which should be after the typescript 5.0 beta comes out, which should be by the end of the month!
