### ISSUE TITLE
[FEATURE] something like $$cond macro

### ISSUE THREAD

**Issue by darky** [GoogleFeud/ts-macros#38]
**Is your feature request related to a problem? Please describe.**
I want to extract some boolean on compile time via TS AST and emit one or another code.

**Describe the solution you'd like**
```ts
function $testMacro(param?: number) {
  return $$cond!(
    (ctx, paramAst) => !!paramAst, // params similar $$raw; check that param passed
    () => $$escape(() => {
      // code for passed number `param`
    }),
    () => $$escape(() => {
      // code for undefined `param`
    }),
  )
}
```

**Describe alternatives you've considered**
I don't understand how to implement example above :point_up: using existing instruments now (v2.0.1). Please, provide workaround how to implement conditional macros

**Comment by GoogleFeud** [comment]
Hello! Generally, you can just write the code as if it's in a normal function, and ts-macros will be able to eliminate any unnecessary conditions, for example:
```ts
function $test(num?: number) {
    if (num === undefined) {
        console.log("Nothing was passed to the function!");
    } else {
        console.log(`${num} was passed!`);
    }
}

$test!(123); // console.log(`${123} was passed!`);
$test!(undefined); // console.log("Nothing was passed to the function!");
```
However, I've noticed that not passing anything doesn't remove the unnecessary condition, so that's definitely a bug that'll get fixed asap!

**Comment by darky** [comment]
Thanks!
