### ISSUE TITLE
[BUG] bugs with conditional macros

### ISSUE THREAD

**Issue by darky** [GoogleFeud/ts-macros#39]
**Describe the bug**
Conditional macro not working with:
* Empty argument (should be inferred as `undefined`)
* typeof symbol not working
* discriminated union not working (case for `{obj: true}`)

**Code to reproduce**
https://googlefeud.github.io/ts-macros/playground/?code=FAehAIEkDsBcFMBOBDAxrAlgN3uADgDbICeA5ogPYCu0AJgISgQDqiGC4x1i4qFtuABZJcyOuADO8XLGHhYKaBLwYC8WuETwJVArAB0TcAEECBecTzbwYjQDMa6DBSXg7lALby5BDACMURGIbLRsCLWRaYIwPPApEBAZgYAdoJxdwABIFYgAKLGQCAH4ALnBoKg8-JHAAH0liKopzeokFDGhSOvAAbwo-ACsyhSp4AF8ASl7gcFnwDDtwfMLwAF5V8t0CKZ6Zuf2+JWb4fQIKUlyAcgqzcHjwGgE7DvVLiYBuPdmxr-nF3NglngFEWBXM6w210q1UQb2m+wOLgkx1O5yuFSqSDen32P32CyWgKsIPAYLW63AlwkjT8zThuwRc0OyLUqIuVJpdI+vzxcwJAKBJLJEMpbTYnXpv0RR1ZZ3ZYo6pGxPN+-LJ9A2N3MADJtRZiaCVhrIRiYZdwLr9cDDeZjaL2hKLXqidbSUaKRymgRJYzZsyUXKrv0hvJEKNlbjgD9gLlclNVgA+eFMpGwGxrLI5ej5CgYDQABm50ra4D8GeyQWzH3AYHAAHdKJ1wL9mWnUOWs7kAIwAJgAzEWU0o0xoNhXiNmAMqcghXACOdfgb2rtYbLlILdT4FwY87lwXS8Hfq3i13ldyfUGwzD4ymq8bG8mnyAA

**Comment by GoogleFeud** [comment]
Hello! Passing nothing to an optional parameter is going to expand to the name of the parameter, which is definitely a bug, which we found out in #38.

ts-macros doesn't consider symbols as literals and does nothing to detect them, which is why `typeof Symbol(...) === "symbol"` doesn't get removed. Sort of the same thing happens with objects, they only get considered literals when used in access expressions.

I suggest using the `$$typeToString` macro instead of relying on literals, then your code will work even if a literal isn't passed to the function!

**Comment by darky** [comment]
Can you please provide example, how I can discriminate union using `$$typeToString`?
As I see, `$$typeToString` doesn't help with proper type detection:

```ts
function $try(val?: number) {
  $$typeToString!<typeof val>();
}

$try!(123); // "number | undefined"
$try!(); // "number | undefined"
$try!(void 0); // "number | undefined"
```

**Comment by GoogleFeud** [comment]
You can use type parameters with `$$typeToString` to use it reliably ([example](https://googlefeud.github.io/ts-macros/playground/?code=FAehAIEkDsBcFMBOBDAxrAlgN3uADgDbICeA5ogPYCu0AJgISgQDqiGC4x1i4qFtuABZJcyOuADO8XLGHhYKaBLwYC8WuETwJVArAB0TcAEECBecTzbwYjQDMa6DBSXg7lALby5BDACMURGIbLRsCLWRaYIwPPApEBAZgYAdoJxdwABIECVgAHgAVAD4ACixkAgB+AC5wAoBKcABvYHA2rOzLeAKKAGUFDGhSekLS+oBuYABfZOBs7Vh6EoAiAEYAJgBmZYnwMEkBofAAH3AaATtB9TmcxZKNzd396CoPPyQTs7p4S+hr+dySwUVHgTwgfgoFDUYk+5x+V1oNwWSyayFqDymYOaNlqLzeSHG4CmsO+v2uQA)). However the parameter being optional makes it so the result of `$$typeToString` always include undefined. You can make the parameter required and then it should work as expected.

In the next update, `$$typeToString` will accept an argument to make the resulting type non-nullable (so `number | undefined` => `number`), so it'll work even when the parameter is optional.

**Comment by darky** [comment]
Thanks!
