### ISSUE TITLE
[BUG] array destruction not working with $$inlineFunc

### ISSUE THREAD

**Issue by darky** [GoogleFeud/ts-macros#40]
**Describe the bug**
If using array destruction, `$$inlineFunc` can't handle array alias

**Code to reproduce**
https://googlefeud.github.io/ts-macros/playground/?code=GYVwdgxgLglg9mABAEigJwJ4AoCGa0BciYIAtgEYCmaA2gLoA0iE5RWYRJF1AlIgLwA+YmSq06fAN4AoRMwQBnKIjxocGASvwBuWfLBLENMAEYmYAEx1NyZDDAAbe5QBi4CAEIsLJqvU0ABglEAHoQxAB3NAQAcz0IRWU0SgUABxs7R2c3SC8fLTUMQOCwxGBnaQBfaWlUTC8aM0QrJnY+ISMkAGpEJu7miWkgA

**Comment by GoogleFeud** [comment]
Good catch, fixed in the next update.
