### ISSUE TITLE
Is there a y plans to support other than webpack bundlers: vite, esbuild?

### ISSUE THREAD

**Issue by vedmalex** [GoogleFeud/ts-macros#43]
Library is perfect !
Is there a y plans to support other than webpack bundlers: vite, esbuild?

**Comment by GoogleFeud** [comment]
Hello! As long as the bundler you're using supports plugins, a `typescript` plugin should allow you to run this transformer.

For vite there's [@rollup/plugin-typescript](@rollup/plugin-typescript).

**Comment by vedmalex** [comment]
Can you mention this in documentation?

I found this project through chatGPT :) And it says that pitfalls of ts-macro that in is not supported in all bundlers :)

**Comment by vedmalex** [comment]
> For vite there's [@rollup/plugin-typescript](@rollup/plugin-typescript).
Will try it

**Comment by GoogleFeud** [comment]
> Can you mention this in the documentation?
> 
> I found this project through chatGPT :) And it says that the pitfalls of ts-macro are that it is not supported in all bundlers :)

Yeah, I'll make sure to add that to README in the next update! Also, it's hilarious that you found out about the library from chatGPT of all places! It probably said that because we've had issues in the past with some bundlers' plugins.
