### ISSUE TITLE
[FEATURE] incremental compilation support

### ISSUE THREAD

**Issue by noname0310** [GoogleFeud/ts-macros#46]
**Is your feature request related to a problem? Please describe.**
There was a problem implementing hot reloading using gulp-typescript.

https://github.com/ivogabe/gulp-typescript#incremental-compilation
when performing an hot reloading in the way that you see in this document,
the entire project is recompiled when hot reloading, which takes a very long time.

The gulp-typescript recompiles only for source files that have changed if the `isolatedModules` option is true. 
Transformers do not receive `ts.Program` instances at this time. Therefore, ts-macros cannot work.

**Describe the solution you'd like**
Is it possible to implement an optionally receive program parameters from Transformers and cache the first compilation type info results?
Maybe the direction of my question itself is wrong. I'm sorry in advance.

**Describe alternatives you've considered**
none

**Additional context**
I'm not sure if this is just a gulp-typescript's incremental compilation problem.

**Comment by GoogleFeud** [comment]
Hi! I've never used gulp so I'm not entirely sure how it works with the typescript compiler, but I think a `Program` instance is required for a typescript file to be transpiled, so transformers should be able to always receive it.

Maybe take this over to gulp-typescript and I'll try to do something if it's not an issue on their end!

**Comment by noname0310** [comment]
Wait a minute, I'll make a small sample project that reproduces the error.

**Comment by noname0310** [comment]
https://github.com/noname0310/gulp-typescript-ts-macros-test

Here is a sample project that reproduces the error. I wrote the cause of the error in `gulpfile.ts`.

**Comment by GoogleFeud** [comment]
Thanks for the example repo! I went over gulp-typescript's source and I found out why a `Program` doesn't get passed:

If `isolatedModules` is set to `true` gulp-typescript uses the `transpileModule` method, which gives you no direct access to a `Program`:

```ts
		const output: ts.TranspileOutput = this.project.typescript.transpileModule(file.content, {
			compilerOptions: this.project.options,
			fileName: file.fileNameOriginal,
			reportDiagnostics: true,
			transformers: this.finalTransformers ? this.finalTransformers() : undefined,
		});
```

`this.finalTransformers` is the `getCustomTransformers` function you create in the gulpfile.

So yes right now if you have `isolatedModules` set to `true` you won't be able to use any transformers which require a `Program` instance, but not because there's a limitation or anything like that. The maintainers of gulp-typescript can create the `Program` themselves and pass it to `this.finalTransformers` (just like they do if `isolatedModules` is false), but instead they've decided to use `transpileModule`. Maybe there is a reason for this, it might be better to ask them.

**Comment by noname0310** [comment]
Okay, if so, can I write a hot reload script using the typescript api directly without using the `gulp-typescript`?

**Comment by GoogleFeud** [comment]
If you mean watching typescript files and transpiling them when there's a change - have a watcher which watches files for changes -> use the typescript API (`Program`, not `transpileModule`) to transpile the code -> write the output to the file. [Here](https://github.com/GoogleFeud/ts-macros/blob/main/playground/utils/transpile.ts#L92)'s an example taken from the playground which uses `Program` to transpile a string.

Hot reloading as in transpiling the typescript code and updating it while your app keeps all its state... no clue without any other tool.

**Comment by noname0310** [comment]
Thanks. I'll reopen the issue if there's a similar problem

**Comment by noname0310** [comment]
I attempted to solve the problem today and realized that implementing a custom watch is not simply a matter of a few lines of code. As a user who uses ts-macro and is experiencing issues with gulp-typescript's incremental compilation, it seems impossible to use watch when building with other toolchains such as terser or babel.

As far as I know, the only solution to use terser and babel together in watch mode is through gulp. Are there any other ways to achieve this?

https://github.com/js-sdsl/js-sdsl/blob/main/tools/buildFactory.ts#L148
This is the current build script that uses ts-macro. I brought it here to illustrate the specific problem state.

**Comment by GoogleFeud** [comment]
I wish I could help but I've never used any of these tools, it would be better to ask someone who understands more about them.
