### ISSUE TITLE
[BUG] Unhandled SyntaxKind: Unknown (regression?)

### ISSUE THREAD

**Issue by vfsfitvnm** [GoogleFeud/ts-macros#54]
Hi again.

**Describe the bug**
When using version `2.2.1` (with either `ts-patch@3.0.0-beta2` or `ttsc@0.3.1`), I get that cryptic error when I use a certain macro (`$$readFile` for instance) in certain scenarios.

**Code to reproduce**
Apparently, we cannot use `$$readFile` in a namespace...
```ts
// ❌ error.ts
import { $$readFile } from "ts-macros";

namespace Foo {
  $$readFile!("src/index.ts");
}
```
or in a object literal AND in a class...
```ts
// ❌ error.ts
import { $$readFile } from "ts-macros";

const Foo = {
  a: $$readFile!("src/index.ts"),
};

class Bar {
  foo() {
    $$readFile!("src/index.ts");
  }
}
```
but we can use `$$ts` inside a namespace...
```ts
// ✅ fine.ts
import { $$ts } from "ts-macros";

namespace Foo {
  $$ts!(";");
}
```
or `$$readFile` in a object literal...
```ts
// ✅ fine.ts
import { $$readFile } from "ts-macros";

const Foo = {
  a: $$readFile!("src/index.ts"),
};
```
or `$$readFile` in a class...
```ts
// ✅ fine.ts
import { $$readFile } from "ts-macros";

class Bar {
  foo() {
    $$readFile!("src/index.ts");
  }
}
```
**Expected behavior**
-

**Additional context**
Doesn't occur in `2.1.0`. Not sure if this is related to `ts-patch` or `typescript=^5`.

**Comment by GoogleFeud** [comment]
Thanks for the bug report! There's indeed a bug regarding namespace members (your first example), and also a `$$readFile` bug that returns a raw string instead of a string literal if the file is being read more than once (second example).

Will be fixed in the next patch!
