### ISSUE TITLE
[BUG] ESM type imports are not modified by compiler

### ISSUE THREAD

**Issue by koerismo** [GoogleFeud/ts-macros#56]
**Describe the bug**
ESM imports that contain the `type` keyword are not modified by the compiler when the transform is enabled.

**Code to reproduce**
```ts
import type { foo } from './test.js';
import { bar, type baz } from './test.js';
```

**Expected behavior**
Imports should be modified by the compiler to only include "real" imports.
The above example should compile to the following:
```js
import { bar } from './test.js';
```

**Additional context**
*Note: This issue also occurred while using ttypescript (`@1.5.15`) with typescript (`@4.9.5`).*
Version info:
```
ts-macros@2.2.2
ts-patch@3.0.1
typescript@5.1.6
```

**Comment by GoogleFeud** [comment]
Thanks for the bug report!
