### ISSUE TITLE
Imports are not working inside $$raw macro

### ISSUE THREAD

**Issue by jmmaa** [GoogleFeud/ts-macros#58]
Hello, I've been dabbling around the lib for a while. I just wanna know how to make imports work inside the `$$raw` macro.

Here is an example

```typescript
import { $$raw, RawContext } from "ts-macros";
import * as fs from "fs";

export function $writeMyFile(): string {

  return $$raw!((ctx: RawContext) => {
    const myfile = fs.readFileSync('file.txt', 'utf8')

    return ctx.factory.createStringLiteral(myfile.toString());
  });
}
```
But this macro does not compile and gives me an error
```
$fs is not defined
9     var css = fs.readFileSync('file.txt', 'utf8');
```
I'm aware that `$$readFile` macro exists, but I wanted to do something beyond that (which includes writing, using third party libs, etc.). I'd also be grateful to have an insight on how does `$$raw` macro actually work, since it gives me some issues to (just like this one) which are non-existent outside of its scope.

**Comment by GoogleFeud** [comment]
Hello! So, essentially, `raw` stringifies the function you pass to it and executes it during the transpilation, which means you cannot use any variables or functions that are outside the function.

You can import `fs` with `require` inside the macro callback and it should work just fine!

**Comment by jmmaa** [comment]
> You can import `fs` with `require` inside the macro callback and it should work just fine!

It gives me this error..
```
$$raw in $writeMyFile: require is not defined

4     var fs = require("fs");
              ~~~~~~~~
              ~~~~~~~~
```

Here is the whole macro

```typescript
export function $writeMyFile(): string {
  return $$raw!((ctx: RawContext) => {
    const fs = require("fs");

    const myfile = fs.readFileSync("file.txt", "utf8");

    return ctx.factory.createStringLiteral(myfile.toString());
  });
}
```

**Comment by GoogleFeud** [comment]
Interesting, I thought global variables provided by node are accessible inside these functions. I will add the `require` function and several others to `ctx` so you'll be able to use them!

**Comment by jmmaa** [comment]
> Interesting, I thought global variables provided by node are accessible inside these functions. I will add the `require` function and several others to `ctx` so you'll be able to use them!

Alright, I look forward to this!

On a side note though, this might be a naive answer but would it make sense to use `eval()` function for `$$raw` and `$$comptime` macros?
