### ISSUE TITLE
[DOCS] `ttypescript` have issued a deprecation notice for TS^5.0

### ISSUE THREAD

**Issue by WillsterJohnson** [GoogleFeud/ts-macros#59]
According to https://github.com/cevek/ttypescript/commit/0c36bbfd76f134dd7275e8d0f86458fbf94bf370, ttypescript will no longer be receiving updates for typscript 5.0 and above.

Its probably best to update the README here accordingly.

**Comment by GoogleFeud** [comment]
Thanks, will update the README in the next update :)
