### ISSUE TITLE
[FEATURE] Provide a convenient way to generate an export with a specific desired identifier.

### ISSUE THREAD

**Issue by gwhitney** [GoogleFeud/ts-macros#65]
**Is your feature request related to a problem? Please describe.**
I am writing a macro which should, among other things, export an identifier specified in the macro call. I can't seem to find a way to do this. In particular, function bodies are not allowed to export identifiers, so it seems I need to use the `$$ts` builtin macro, but if I write e.g. 
```
$$ts!(`export const ${name} =  ${desired_value};`)
```
the identifier is mangled presumably for hygienic reasons. I suspect that I could use $$raw to do this, but it is hard to find good documentation on how to use factory.createExportAssignment or factory.createExportDeclaration. If you think it's best to do this with $$raw rather than add a facility for exporting, I respect that but if you have any pointers to information about how to use the Compiler API for something like this they would be welcome.

**Describe the solution you'd like**
I could imagine several designs, but I think the easiest to use would be another flag on $$define which specifies whether to export the definition, defaulting to false. Another possibility would be an "unhygienic" option to $$ts. Yet a third option would be an explicit $$export built-in macro. 

**Describe alternatives you've considered**
I believe these are covered above.

**Additional context**
If a PR would help make this happen I am willing to try even though I am almost completely unfamiliar with the TypeScript Compiler API. But for this, I'd need an indication of the desired design for allowing exports. And if you have any suggestions for useful resources to get intformation about the TypeScript API it would be appreciated.

**Comment by GoogleFeud** [comment]
I think it's a good idea to add such an option to the `$$define` macro, it's a simple change if you know the compiler API so I've gone ahead and added it :)

There isn't really much documentation on the typescript transformer API, it's mostly tinkering with it and seeing what works and what doesn't, but here's a good starting point: https://github.com/itsdouges/typescript-transformer-handbook

The typescript AST playground is also really good for experimenting and seeing what data each node/symbol/type has: https://ts-ast-viewer.com/#code/FAYw9gdgzgLgBADzgXjgJgNzCA

The next version will be coming very soon but in the meantime, you can use the `$$raw` version:
```ts
function $export(name: string, value: unknown) {
   $$raw!((ctx, name: ts.Expression, value: ts.Expression) => {
      if (!ctx.ts.isStringLiteral(name)) throw ctx.error(name, "Expected a string literal.");
       return ctx.factory.createVariableStatement([ctx.factory.createToken(ctx.ts.SyntaxKind.ExportKeyword)], ctx.factory.createVariableDeclarationList([
         ctx.factory.createVariableDeclaration(name.text, undefined, undefined, value)
     ], ctx.ts.NodeFlags.Const));
   });
}
```

**Comment by gwhitney** [comment]
Thanks for the quick turnaround and for the upcoming update! I'll give the raw version a try.

**Comment by gwhitney** [comment]
Hmm, when I add

```
// From the creator of ts-macros; temporary until next release
function $export(name: string, value: unknown) {
   $$raw!((ctx, name: ts.Expression, value: ts.Expression) => {
      if (!ctx.ts.isStringLiteral(name)) throw ctx.error(name, "Expected a string literal.");
       return ctx.factory.createVariableStatement([ctx.factory.createToken(ctx.ts.SyntaxKind.ExportKeyword)], ctx.factory.createVariableDeclarationList([
         ctx.factory.createVariableDeclaration(name.text, undefined, undefined, value)
     ], ctx.ts.NodeFlags.Const));
   });
}

$export!("fred", 3)
```

to my file (as well as the necessary imports), and execute tsc, I get:

```
/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:118051
              throw e;
              ^

Error: Debug Failure. Unhandled SyntaxKind: VariableStatement.
    at pipelineEmitWithHintWorker (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:112071:13)
    at pipelineEmitWithHint (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:111615:9)
    at pipelineEmitWithComments (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:115399:7)
    at pipelineEmit (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:111564:7)
    at emitExpression (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:111548:7)
    at emitExpressionStatement (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:113077:7)
    at pipelineEmitWithHintWorker (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:111759:20)
    at pipelineEmitWithHint (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:111615:9)
    at pipelineEmitWithComments (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:115399:7)
    at pipelineEmit (/home/glen/code/typocomath/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/tsc.js:111564:7)
```

Guess I should just wait til the next release? (It's totally OK for me to wait, just posting this info in case it's helpful to you. Thanks again.)

**Comment by GoogleFeud** [comment]
The snippet I provided is incorrect because currently to make it work you have to return an array literal from the `$$raw` function, which will no longer be the case in the next update, sorry! Here's the code which works in the current version:

```ts
function $export(name: string, value: unknown) {
   $$raw!((ctx, name: ts.Expression, value: ts.Expression) => {
      if (!ctx.ts.isStringLiteral(name)) throw ctx.error(name, "Expected a string literal.");
       return [ctx.factory.createVariableStatement([ctx.factory.createToken(ctx.ts.SyntaxKind.ExportKeyword)], ctx.factory.createVariableDeclarationList([
         ctx.factory.createVariableDeclaration(name.text, undefined, undefined, value)
     ], ctx.ts.NodeFlags.Const))];
   });
}
```

**Comment by gwhitney** [comment]
Ah, so there is a hitch. If `testExp.ts` contains this definition of $export and the call:
```
$export!('fred', 7)
```
and the contents of `testImp.ts` are:
```
import * as tst from './testExp.js'

console.log('Fred is', tst.fred)
```

then the combination fails to compile, with the error:
```
src/testImp.ts:3:28 - error TS2339: Property 'fred' does not exist on type 'typeof import("/home/glen/code/typocomath/src/testExp")'.

3 console.log('Fred is', tst.fred)
                            ~~~~

Found 1 error in src/testImp.ts:3
```
So I guess TypeScript doesn't ever find out about the export -- you did say in the documentation that the transform takes place after the typechecking stage. Any way around this snag, or should I just give up on the idea of the macro generating the export? Obviously I need to be able to use the exported symbol from other TypeScript modules... Thanks for your thoughts.

**Comment by GoogleFeud** [comment]
> So I guess TypeScript doesn't ever find out about the export -- you did say in the documentation that the transform takes place after the typechecking stage.

Yeah, the transformer alone cannot do anything because by the time it's run the error is already registered, however, there is a way around this and I'm planning on solving this exact issue really soon!

**Comment by gwhitney** [comment]
All right, we will be watching for future releases. Thanks for all of your help.

**Comment by GoogleFeud** [comment]
[Version 2.4.0 adds a new transformer that fixes this issue!](https://github.com/GoogleFeud/ts-macros/wiki/Type-Resolver-Transformer)

If you have any questions feel free to start a discussion or create an issue!
