### ISSUE TITLE
[BUG] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by matthew-dean** [GoogleFeud/ts-macros#66]
**Describe the bug**
I'm using `XRegExp` to build complex / nested regular expressions. I'm investigating using `ts-macros` for this purpose.

**Code to reproduce**
```ts
import * as XRegExp from 'xregexp'

const $buildFragments = (rawFragments: string[][]) => {
  const fragments: Record<string, RegExp> = {}
  rawFragments.forEach(fragment => {
    fragments[fragment[0]] = XRegExp.build(fragment[1], fragments)
  })
  return fragments
}

const fragments: Record<string, RegExp> = $buildFragments!(rawFragments)
```
(Fragments are regex strings like:)
```ts
const fragments = () => [
  ['newline', '\\n|\\r\\n?|\\f'],
  ['whitespace', '[ ]|\\t|{{newline}}'],
  ['ws', '{{whitespace}}+'],
  ['comment', '\\/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*\\/'],
  ['hex', '[\\da-fA-F]'],
  ['unicode', '\\\\{{hex}}{1,6}{{whitespace}}?']
]
```

**Expected behavior**
I expected a static object to be output with a map of regular expressions.

**Additional context**

**Comment by GoogleFeud** [comment]
Thanks for the bug report! You can only define macros with the `function` keyword, the code below works correctly:
```ts
function $buildFragments(rawFragments: string[][]) {
      const fragments: Record<string, RegExp> = {}
      rawFragments.forEach(fragment => {
      fragments[fragment[0]] = XRegExp.build(fragment[1], fragments)
  })
  return fragments
}
```

However there's definitely something wrong going on if you try to declare it as an arrow function, I'll look into it!

**Comment by matthew-dean** [comment]
@GoogleFeud Ohhhh ha, I didn't think of that, thanks!
