### ISSUE TITLE
[BUG] Module augmentation causes import to be tree-shaken (is removed from output)

### ISSUE THREAD

**Issue by matthew-dean** [GoogleFeud/ts-macros#72]
I'm not certain this is a ts-macros bug or a ts-patch bug, but my perception would be that:
1. ts-patch shouldn't be doing anything except allowing patching (unless that's incorrect)
2. ts-macros is the only transformer I'm using

The bug and all its details are [here](https://github.com/microsoft/TypeScript/issues/55481).

To re-summarize:
```ts
// chevrotain.d.ts
declare module 'chevrotain' {
  interface CstParser {
    // things that augment this type
  }
}


// cssParser.ts
import { CstParser, EOF } from 'chevrotain'

class CssParser extends CstParser {
 // class implementation
}

// outputs
import { EOF } from 'chevrotain'
```
Someone on the TypeScript team investigated and said that disabling ts-patch (which disables ts-macros) solves this bug.

**Comment by GoogleFeud** [comment]
Hello! Yes, the issue is definitely coming from this library, thanks for the bug report!

**Comment by matthew-dean** [comment]
I had ts-macros causing this again with this kind of export. One of my packages exports this:
```ts
export type IdentRole = 'property' | 'variable' | 'selector' | 'keyword';
export declare const Ident: GeneralConstructor<"Ident", IdentRole>;
export type Ident = InstanceType<typeof Ident>;
export declare const UrlValue: GeneralConstructor<"UrlValue", undefined>;
export type UrlValue = InstanceType<typeof UrlValue>;
export declare const Flag: GeneralConstructor<"Flag", undefined>;
export type Flag = InstanceType<typeof Flag>;
export declare const CustomProp: GeneralConstructor<"CustomProp", undefined>;
export type CustomProp = InstanceType<typeof CustomProp>;
export declare const AtKeyword: GeneralConstructor<"AtKeyword", undefined>;
export type AtKeyword = InstanceType<typeof AtKeyword>;
```

Another package had:
```
import { Ident, AtKeyword } from [otherpackage];
```
At compile time, it looks like ts-macros erases Ident and AtKeyword from the import. Other class value imports are not affected.

**Comment by matthew-dean** [comment]
It looks like setting `preserveValueImports` and `verbatimModuleSyntax` don't fix this.
