### ISSUE TITLE
[BUG] ts-macros tries to evaluate a function as a macro when it is not preceded by `$`

### ISSUE THREAD

**Issue by matthew-dean** [GoogleFeud/ts-macros#77]
**Describe the bug**
Unfortunately, I have not been able to reduce to a minimal test case.

I have this class:
```ts
export class Operation extends Node<OperationValue> {
  async eval(context: Context): Promise<Node> {
    let [left, op, right] = this.value
    if (!left.operate) {
      throw new TypeError(`Cannot operate on ${left.type}`)
    }
    return await this.evalIfNot(context, async () => {
      if (context.shouldOperate(op)) {
        left = await left.eval(context)
        right = await right.eval(context)
        return left.operate!(right, op, context)
      }
      let node = this.clone()
      node.evaluated = true
      return node
    })
  }
}
```
I am getting the following error when trying to build with TypeScript:

```
error TS8000: No possible candidates for "operate" call

25         return left.operate!(right, op, context)
```

What's confusing is that the documentation seems to imply that a macro always requires a preceding `$` character, which does not exist here. However, when I tried to create a simple test case in the ts-macros playground, I couldn't reproduce it.

I'm refactoring so I don't need a non-null assertion here, but I thought I should report it anyway.

**Comment by GoogleFeud** [comment]
Thanks for the bug report!

**Comment by GoogleFeud** [comment]
Yeah, when a function call is detected the transformer didn't check whether the function starts with `$`, and in the case for macro chaining, this would error.
